Teleportation Options:
  Require item: false
  Take item: false
  Item ID: 368
  Charge player: false
  Charge amount: 10.0
  
Portal Options:
  Charge on creation: false
  Refund on deletion: false
  Creation charge: 30.0
  Deletion return: 10.0
  
#Turn convert to true, make sure your SQL plugins are correct, and run the plugin to convert to flatfile.  
#If you notice any errors PLEASE REPORT THEM. It means your pads have NOT transferred properly.
Storage Options:
  Convert: false
  
MySQLSettings:
  Username: username
  Password: pass
  Database: minecraft
  Hostname: localhost
  Port: 3306
  Table: travelpad