Teleportation Options:
  Require item: false
  Take item: false
  Item ID: 368
  Charge player: false
  Charge amount: 10.0
  
Portal Options:
  Charge on creation: false
  Refund on deletion: false
  Creation charge: 30.0
  Deletion return: 10.0
  
Storage Options:
  #Turn this to true and fill out your previous SQL settings to have your database converted to flatfile.
  Convert: false
  
MySQLSettings:
  Username: username
  Password: pass
  Database: minecraft
  Hostname: localhost
  Port: 3306
  Table: travelpad