author: H31IX
database: false
description: Travelpad plugin for Bukkit.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.h31ix.travelpad.Travelpad
name: TravelPad
startup: postworld
url: http://H31IX.NET/
version: '1.8'
