author: H31IX
database: false
description: Travelpad for Bukkit
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.h31ix.travelpad.Main
name: TravelPad
startup: postworld
url: http://H31IX.NET/
version: '1.7'
commands:
  travelpad:
    description: Use travelpad
    usage: /travelpad
