Teleportation Options:
  Require item: false
  Take item: false
  Item ID: 368
  Charge player: false
  Charge amount: 10.0
  
Portal Options:
  Charge on creation: false
  Refund on deletion: false
  Creation charge: 30.0
  Deletion return: 10.0
  Allow any player to break: false
  Emit water on creation: true
  #49 = Obsidian 45 = Brick
  Center block id: 49
  Outline block id: 45